spring.application.name=TODO

spring.datasource.url=${PSQL_URL}
spring.datasource.username=${PSQL_USERNAME}
spring.datasource.password=${PSQL_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql = true

spring.data.redis.host=redis-14274.crce206.ap-south-1-1.ec2.cloud.redislabs.com
spring.data.redis.port=14274
spring.data.redis.password=VAIPVvdonB2FirdgyHBHqCe3zSmb50S6
spring.data.redis.username=default

spring.cache.type=redis
spring.cache.redis.time-to-live=600000

logging.level.org.springframework.web=ERROR
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=OFF
